{"name": "test_login_error[data0]", "status": "passed", "steps": [{"name": "获取返回的登录页面", "status": "passed", "start": 1567168072461, "stop": 1567168072461}, {"name": "输入错误的用户名与密码，点击登录", "status": "passed", "start": 1567168072461, "stop": 1567168073992}, {"name": "获取登录失败后的错误提示", "status": "passed", "start": 1567168073992, "stop": 1567168074525}, {"name": "断言", "status": "passed", "start": 1567168074525, "stop": 1567168074546}], "parameters": [{"name": "data", "value": "{'username': '18948956547', 'pwd': '123', 'expected': '此账号没有经过授权，请联系管理员!'}"}], "start": 1567168072461, "stop": 1567168074546, "uuid": "fe05ed78-1cfd-468c-8854-0931c2f4c70f", "historyId": "63777be20473fd7c19a11ae1449a9b27", "testCaseId": "0d76f03330ef19c969af1bc2c1c2d1ce", "fullName": "test_login.TestLogin#test_login_error", "labels": [{"name": "story", "value": "登录失败用例"}, {"name": "feature", "value": "测试登录功能"}, {"name": "tag", "value": "error"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SKY-20190827LKX"}, {"name": "thread", "value": "51860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}